var members=[{
    name: "王晓光",
    id: "friendi",
    qq: 23058720,
    belong: "1",
    say: "一定要改题，不能抄代码，比赛都得打",
    photo: "wxg.jpg",
    school: "东北师范大学附属中学",
    major: "特级教练员",
    wechat: "13844055086",
},{
    name: "王昌平",
    id: "net_assassin",
    qq: 903484399,
    belong: "1",
    say: "就那啥嘛，一横一竖，然后gzotpa",
    blog: "https://blog.csdn.net/net_assassin/",
    photo: "wcp.jpg",
    school: "东北师范大学附属中学",
    major: "高级教练员",
    wechat: "15948756996",
},{
    name: "孔维玲",
    id: "ling",
    qq: 147729099,
    belong: "1",
    say: "我替学校谢谢你们",
    photo: "kwl.jpg",
    school: "东北师范大学附属中学",
    major: "特级教练员",
    wechat: "kwling123",
},{
    name: "任雪亮",
    id: "moonlight131",
    qq: 703180800,
    belong: "1",
    say: "你斜~的吗",
    photo: "rxl.jpg",
    school: "东北师范大学附属中学",
    major: "一级教练员",
},{
    name: "孙雪晖",
    id: "zidaneandmessi",
    belong: "2016, 8",
    say: "咦我爱死机构爱死机构我价格加瓦儿歌",
    qq: 328349206,
    twitter: "zidaneandmessi",
    bilibili: 7929890,
    github: "zidaneandmessi",
    weibo: "zidaneandmessi",
    blog: "https://zidaneandmessi.github.io/",
    school: "",
    major: "",
},{
    name: "邹雨恒",
    id: "KuribohG",
    belong: "2016, 2",
    say: "爱情似屏幕，dfs求最短路",
    qq: 972646347,
    school: "",
    major: "",
},{
    name: "尹一航",
    id: "someday",
    belong: "2016, 13",
    say: "今天就真的退役了，JL的孩子们啊，不要忘了Someday曾经也是一名OIer，OI再见。",
    qq: 714439471,
    school: "",
    major: "",
},{
    name: "李思航",
    id: "lisihang",
    belong: "2016, 2",
    say: "",
    qq: 1029076022,
    photo: "lsh.jpg",
    school: "北京大学",
    major: "",
},{
    name: "尚柯宇",
    id: "devilily",
    belong: "2016",
    say: "我要揍你",
    qq: 569668658,
    school: "",
    major: "",
},{
    name: "李雪欣",
    id: "ISummerx",
    belong: "2016",
    say: "",
    qq: 814967611,
    school: "",
    major: "",
},{
    name: "徐瑞帆",
    id: "xuruifan",
    belong: "2017, 2",
    say: "靠！你是不是傻逼！",
    qq: 707185547,
    bilibili: 19206494,
    blog: "http://www.cnblogs.com/xuruifan",
    school: "北京大学",
    major: "计算机科学与技术",
},{
    name: "王子航",
    id: "wzh1",
    belong: "2017, 3",
    say: "",
    qq: 1213075831,
    school: "清华大学",
    major: "",
},{
    name: "甄瑞航",
    id: "ZMiG",
    belong: "2017",
    say: "",
    qq: 1823526105,
    bilibili: 19213104,
    school: "",
    major: "",
},{
    name: "王焱",
    id: "Thr__Fir_s",
    belong: "2017",
    say: "",
    qq: 1012534745,
    bilibili: 8132294,
    school: "",
    major: "",
},{
    name: "聂恺辰",
    id: "commonc",
    belong: "2018, 2",
    say: "聂恺辰 第二天t1 输出格式错误",
    qq: 904095866,
    bilibili: 20974730,
    blog: "https://blog.csdn.net/commonc",
    photo: "nkc.jpg",
    school: "北京大学",
    major: "智能科学与技术",
},{
    name: "李佳实",
    id: "ljss",
    belong: "2018, 2",
    say: "/+v",
    qq: 450993438,
    school: "北京大学",
    major: "计算机科学与技术",
},{
    name: "姜淳誉",
    id: "neither",
    belong: "2018, 3",
    say: "就让我永远不在这里写什么有意义的话",
    qq: 859985722,
    bilibili: 32740908,
    blog: "https://blog.csdn.net/neither_nor",
    school: "清华大学",
    major: "计算机科学与技术",
    photo: "jcy.jpg",
},{
    name: "程傲",
    id: "Oakley",
    belong: "2018, 9",
    say: "",
    qq: 136808543,
    blog: "https://blog.csdn.net/Oakley_",
    school: "上海大学",
    major: "",
},{
    name: "尹涵",
    id: "ahcisy",
    belong: "2018, 3",
    say: "",
    qq: 2586669575,
    blog: "https://blog.csdn.net/ahcisy",
    school: "清华大学",
    major: "",
},{
    name: "白济明",
    id: "Raidriar",
    belong: "2018, 11",
    say: "独者轻孤，孤者慎独",
    qq: 1085455474,
    blog: "https://blog.csdn.net/bjmbjmbjmbjm",
    school: "北京邮电大学",
    major: "网络空间安全专业",
},{
    name: "吴佳奕",
    id: "BeyondW",
    belong: "2018, 6",
    say: "I'll still be thinkin' of you and the times we had",
    qq: 1820092536,
    blog: "https://blog.csdn.net/BeyondW__",
    school: "天津大学",
    major: "电子科学与技术",
    photo: "wjy.jpg",
},{
    name: "苑文雨",
    id: "foreverywy",
    belong: "2018, 5",
    say: "神犇就我啊",
    qq: 1793432088,
    school: "哈尔滨工业大学（深圳）",
    major: "环境科学与工程",
    photo: "ywy.jpg",
},{
    name: "唐熙霖",
    id: "_blackjack_",
    belong: "2019, 12",
    say: "Whatever.",
    qq: 1280814449,
    blog: "https://blog.csdn.net/blackjack_/",
    photo: "txl.jpg",
    school: "中国人民大学",
    major: "计算机科学与技术",
},{
    name: "吕昆航",
    id: "komqaq",
    belong: "2019, 2",
    say: "梦醒了。",
    qq: 1047963985,
    blog: "http://kylelv.com/",
    school: "北京大学",
    major: "计算机科学与技术",
},{
    name: "赵广泽",
    id: "l1ll5",
    belong: "2019, 4",
    say: "",
    qq: 2817629709,
    bilibili: 1519204,
    blog: "https://zgz233.xyz/",
    school: "浙江大学",
    major: "计算机科学与技术",
},{
    name: "张翔睿",
    id: "dreamy_melody",
    belong: "2019, 7",
    say: "时空将你我连接，信息将你我分开||我从梦幻而生，终将坠入梦幻",
    school: "吉林大学",
    major: "计算机科学与技术",
    qq: 1921969766,
},{
    name: "王知非",
    id: "a799091501",
    belong: "2019, 11",
    say: "",
    qq: 3214341071,
    blog: "http://www.cnblogs.com/tsunderehome/",
    school: "北京邮电大学",
    major: "物联网工程",
},{
    name: "赵春源",
    id: "Claire",
    belong: "2020, 2",
    say: "很多年以后，我有一个绰号叫西毒。任何人都可以变得狠毒，只要你尝试过什么叫嫉妒。",
    qq: 1398660594,
    school: "北京大学",
    major: "",
},{
    name: "李凡丁",
    id: "Michael_Bryant",
    belong: "2020, 5",
    say: "这世上，无论多么短暂的瞬间，都有意义",
    qq: 1137892110,
    bilibili: 20040279,
    zhihu: "michael-bryant-34",
    blog: "https://blogmb.com/",
    photo: "lfd.jpg",
    tiktok: "http://blogmb.com/?page_id=1594",
    school: "哈尔滨工业大学",
    major: "英才学院",
},{
    name: "王奕然",
    id: "everlasting",
    belong: "2020, 10",
    say: "现在这个网站好看多了",
    qq: 851627835,
    zhihu: "everlasting-50-41",
    blog: "https://everlasting.wang:8088/",
    school: "福州大学",
    major: "计算机类",
},{
    name: "汤云开",
    id: "Camouflager",
    belong: "2020, 2",
    say: "",
    qq: 2034826488,
    photo: "tyk.jpg",
    major: "信息与计算科学",
    school: "北京大学",
},{
    name: "李一錡",
    id: "thewalker88",
    belong: "2020, 13",
    say: "与我一同踏上霞客之路吧",
    qq: 1145101354,
    music_163: 401293943,
    school: "北京航空航天大学",
    major: "高等理工",
},{
    name: "李天晓",
    id: "starria",
    belong: "2020, 3",
    say: "That is not dead which can eternal lie,and with strange aeons even death may die.",
    qq: 972808330,
    bilibili: 8413874,
    music_163: 599434231,
    school: "清华大学",
    major: "计算机科学与技术",
    photo: "ltx.jpg",
},{
    name: "杜天睿",
    id: "Turtle_King",
    belong: "2020, 7",
    say: "我依舊最喜歡我可愛的妹妹！",
    qq: 1240280333,
    bilibili: 20202543,
    zhihu: "jia-yu-shou-ling",
    school: "吉林大学",
    major: "交通运输类",
},{
    name: "丁奥",
    id: "Dawn_Buendia",
    belong: "2020, 14",
    say: "铁幕重重困青年，自由或许问心脏",
    qq: 1344988745,
    bilibili: 250129967,
    zhihu: "xue-fei-de-yu",
    school: "中国地质大学（北京）",
    major: "工商管理类",
    photo: "da.jpg",
},{
    name: "刘书任",
    id: "lsr",
    belong: "2020, 6",
    say: "身在TJU啥算法都不会了的AFO选手",
    qq: 1409111459,
    bilibili: 382376033,
    photo: "lsr.jpg",
    school: "天津大学",
    major: "计算机科学与技术",
},{
    name: "高鸣宇",
    id: "coldhac",
    belong: "2021, 2",
    say: "让我望而却步的，不是遥远，而是孤独",
    qq: 1635793282,
    zhihu: "xia-xian-lun-hui",
    music_163: 110764168,
    bilibili: 9229336,
    blog: "http://cod.ac.cn",
    school: "北京大学",
    major: "信息与计算科学",
    photo: "gmy.jpg",
},{
    name: "孙嘉伟",
    id: "namespace_std",
    belong: "2022, 2",
    say: "Let all the disappointment go with wind.",
    qq: 1263354661,
    blog: "https://www.luogu.org/blog/3-14159265358/",
    school: "东北师范大学附属中学",
    major: "高三",
},{
    name: "李新年",
    id: "LebronDurant",
    belong: "2022, 2",
    say: "从容中道",
    qq: 727428727,
    blog: "https://www.luogu.org/blog/betrayer/",
    school: "东北师范大学附属中学",
    major: "高三",
},{
    name: "何松谕",
    id: "twilight118",
    belong: "2022, 15",
    say: "我要一步一步往上爬，在最高点乘着叶片往前飞",
    qq: 1785860025,
    school: "东北师范大学附属中学",
    major: "高三",
},{
    name: "姜乃珲",
    id: "jiangnaihui",
    belong: "2022, 16",
    say: "我还有什么话可说呢？",
    qq: 1565909353,
    school: "东北师范大学附属中学",
    major: "高三",
},{
    name: "孙伟哲",
    id: "SourFold",
    belong: "2022, 11",
    say: "这不傻子题",
    qq: 1340364178,
    school: "东北师范大学附属中学",
    major: "高三",
},{
    name: "王恕",
    id: "wolverine",
    belong: "2023",
    say: "",
    qq: 168778017,
    blog: "https://www.luogu.org/blog/wangshu31/",
    school: "东北师范大学附属中学",
    major: "高二",
},{
    name: "刘朔",
    id: "Syzygy12",
    belong: "2023",
    say: "",
    qq: 3232149367,
    blog: "https://84205.blog.luogu.org/",
    school: "东北师范大学附属中学",
    major: "高二",
},{
    name: "李子豪",
    id: "telesto",
    belong: "2023",
    say: "",
    qq: 2145705084,
    school: "东北师范大学附属中学",
    major: "高二",
    blog: "https://www.luogu.com.cn/blog/CorCor-Xor-CorCor/#",
    bilibili: "https://space.bilibili.com/109673045",
},{
    name: "王冠尧",
    id: "Celtic",
    belong: "2024",
    say: "我只想做个与世无争的垃圾，可是还要被分类...",
    qq: 1194239942,
    zhihu: "he-chou-qing-si-pei-bai-yi-40",
    music_163: 3721314120,
    bilibili: 489387130,
    blog: "https://www.cnblogs.com/CelticBlog/",
    school: "东北师范大学附属中学",
    major: "高一",
    photo: "wgy.jpg",
},{
    name: "张铠麒",
    id: "ooooxxxx",
    belong: "2024",
    say: "",
    qq: 2048455641,
    blog: "https://protons-z.github.io/",
    school: "东北师范大学附属中学",
    major: "高一",
    photo: "zkq.jpg",
},{
    name: "袁浩为",
    id: "accoder",
    belong: "2025",
    say: "",
    qq: 2201685475,
    school: "东北师范大学附属中学",
    major: "初三",
},{
    name: "张一鸣",
    id: "swift",
    belong: "2025",
    say: "Write the Code. Change the world.",
    qq: 1149395947,
    zhihu: "swift-zym",
    music_163: 1986415245,
    bilibili: 492358939,
    blog: "https://zhangyiming.tech/",
    school: "东北师范大学附属中学",
    major: "初三",
    photo: "zym.jpg",
},{
    name: "王若溪",
    id: "Rancy",
    belong: "2025",
    say: "",
    qq: 529513043,
    school: "东北师范大学附属中学",
    major: "初三",
},{
    name: "夏铭飞",
    id: "SummerFlyFly",
    belong: "2022, 17",
    say: "Time will prove.",
    qq: 2088874580,
    zhihu: "summerflyfly",
    music_163:2126704369 ,
    bilibili:384767875 ,
    blog: "",
    school: "东北师范大学附属中学",
    major: "高三",
}
/* ,{
    name: "",
    id: "",
    belong: "",
    say: "",
    qq: ,
} */];

for(var i=0; i<members.length; i++){
    var div=document.getElementById("infomation");
    var addHTML="";
    addHTML+="<div class=\"filtr-item w3l-button\" data-category=\""+members[i].belong+"\">";
    addHTML+="<a href=\"#\" data-toggle=\"modal\" data-target=\"#"+members[i].id+"\">";
    addHTML+="<figure class=\"w3ls-gallery\">";
    addHTML+="<img src=\"http://q.qlogo.cn/headimg_dl?bs=qq&dst_uin="+members[i].qq+"&src_uin=www.jlwz.cn&fid=blog&spec=4\" alt=\" \" />";
    addHTML+="<span class=\"text\">"+members[i].name+"</span>";
    addHTML+="<hr>";
    addHTML+="<span class=\"text\">"+members[i].id+"</span>";
    addHTML+="</figure>";
    addHTML+="</a>";
    addHTML+="</div>";
    div.innerHTML+=addHTML;
    
    div=document.getElementById("cards");
    addHTML="<div class=\"modal about-modal fade\" id=\""+members[i].id+"\" tabindex=\"-1\" role=\"dialog\">";
    addHTML+="<div class=\"modal-dialog\" role=\"document\">";
    addHTML+="<div class=\"modal-content\"><div class=\"modal-header\">";
    addHTML+="<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>";
    addHTML+="<h4 class=\"modal-title\">"+members[i].id+"</h4>";
    addHTML+="</div>";
    addHTML+="<div class=\"modal-body\"><div class=\"about\">";
    addHTML+="<div class=\"col-md-4 col-sm-4  col-xs-4 about-left \">";
    if(members[i].photo)addHTML+="<img src=\"photo/"+members[i].photo+"\" class=\"img-responsive\" alt=\"\"/>";
    else addHTML+="<img src=\"photo/empty.jpg\" class=\"img-responsive\" alt=\"\"/>";
    addHTML+="</div>";
    addHTML+="<div class=\"col-md-8 col-sm-8 col-xs-8 about-right wthree\">";
    addHTML+="<h3>"+members[i].name+"</h3>";
    addHTML+="<h4>"+members[i].say+"</h4>";
    addHTML+="<ul class=\"address\">";
    
    addHTML+="<li><ul class=\"agileits-address-text \"><li><b>QQ</b></li><li>"+members[i].qq+"</li></ul></li>";
    if(members[i].wechat)addHTML+="<li><ul class=\"agileits-address-text \"><li><b>微信</b></li><li>"+members[i].wechat+"</li></ul></li>";
    
    if(members[i].bilibili)addHTML+="<li><ul class=\"agileits-address-text\"><li><b>B站uid</b></li><li><a href=\"https://space.bilibili.com/"+members[i].bilibili+"\" target=\"_blank\"> "+members[i].bilibili+"</a></li></ul></li>";
    if(members[i].zhihu)addHTML+="<li><ul class=\"agileits-address-text\"><li><b>知乎</b></li><li><a href=\"http://www.zhihu.com/people/"+members[i].zhihu+"\" target=\"_blank\"> "+members[i].zhihu+"</a></li></ul></li>";
    if(members[i].blog)addHTML+="<li><ul class=\"agileits-address-text\"><li><b>博客</b></li><li><a href=\""+members[i].blog+"\" target=\"_blank\"> "+members[i].blog+"</a></li></ul></li>";
    if(members[i].twitter)addHTML+="<li><ul class=\"agileits-address-text\"><li><b>推特</b></li><li><a href=\"https://twitter.com/"+members[i].twitter+"\" target=\"_blank\"> "+members[i].twitter+"</a></li></ul></li>";
    if(members[i].github)addHTML+="<li><ul class=\"agileits-address-text\"><li><b>github</b></li><li><a href=\"https://github.com/"+members[i].github+"\" target=\"_blank\"> "+members[i].github+"</a></li></ul></li>";
    if(members[i].music_163)addHTML+="<li><ul class=\"agileits-address-text\"><li><b>网易云</b></li><li><a href=\"https://music.163.com/#/user/home?id="+members[i].music_163+"\" target=\"_blank\"> "+members[i].music_163+"</a></li></ul></li>";
    
    addHTML+="</ul>";
    addHTML+="</div>";
    addHTML+="<div class=\"clearfix\"> </div>";
    addHTML+="</div>";
    addHTML+="</div>";
    addHTML+="</div>";
    addHTML+="</div>";
    addHTML+="</div>";
    div.innerHTML+=addHTML;
}